### ISSUE TITLE
Using Metrolog in iOS Results in System.TypeInitializationException

### ISSUE THREAD

**Issue by michaelstonis** [mbrit/MetroLog#50] opened 2014-06-10 19:55 UTC
Metrolog is being called via a PCL from both a Xamarin.Android and Xamarin.iOS project. Each Xamarin project has the corresponding Metrolog.Platform project reference from nuget. 

Calls from Xamarin.Android work without issues.

    Unhandled managed exception: An exception was thrown by the type initializer for MetroLog.LogManagerFactory (System.TypeInitializationException)

**Comment by jojojames** [comment] 2015-01-28 06:12
+1
Seeing this when using:

ILogger Log = LogManagerFactory.DefaultLogManager.GetLogger<AppDelegate>();

**Comment by Grrbrr404** [comment] 2015-02-10 13:26
+1, same issue here

**Comment by onovotny** [comment] 2015-02-10 15:24
In your iOS projects, can you verify that your linker is set to SDK Assemblies only?

**Comment by jojojames** [comment] 2015-02-10 18:53
It is set to 'Link SDK assemblies only'.

**Comment by Grrbrr404** [comment] 2015-02-10 19:06
The problem is Assembly.Load inside of your Loader (Where you load the MetroLog.Platform). The Problem on iOS is, the linker will remove everything that is not needed. So .... I was able to resolve the problem today - Can post a more detailed solution tomorrow.

Btw: It seems your nuget package for the iOS platform os corrupt somehow . At least I am missing the MetroLog.Platform reference on my iOS project after installation of the package. I was only able to solve the issue by downloading your code and then compiled it myself (So that I had the MetroLog.Platform dll of iOS available)

So .. yeah. More details how to solve it on iOS tomorrow

Regards

**Comment by Grrbrr404** [comment] 2015-02-11 08:12
Hi,

the only think I need to do in my Xamarin.IOS App is the following:

		static void Main(string[] args) {
			var iosLinkerTrick = typeof (MetroLog.StreamingFileTarget);
			UIApplication.Main(args, null, "AppDelegate");
		}

This tricks the iOS Linker to force the loading of "MetroLog.Platform.dll" - Otherwise it will get removed. So I was wrong yesterday, Assembly.Load is not the real Problem - problem is iOS Linker removing the dll because it "thinks" it is not required. You can observe  the behavior of the linker in VS output log, not loading the DLL if you remove the steatment.

**Comment by onovotny** [comment] 2015-02-11 13:09
The linker shouldn't be removing referenced files if the SdkOnly option is set -- I know there's currently a bug in the Visual Studio Xamarin UI for this. Can you take a quick look at the csproj file to verify if `<MtouchLink>SdkOnly</MtouchLink>` is in the property group section for the configuration you're using?

**Comment by Grrbrr404** [comment] 2015-02-11 14:45
It was set to <MtouchLink>None</MtouchLink>. Changed it to SdkOnly but I get compiling errors then. It is complaining about another 3rd party lib that can't be resolved anymore.

Failed to resolve "System.Reflection.Assembly System.SystemExtensions::GetAssembly(System.Type)" reference from "another 3rd party lib here"	F4M.App.iOS

**Comment by onovotny** [comment] 2015-10-15 12:27
Closing as this seems resolved. Please reopen if needed.

**Closed by onovotny** 2015-10-15 12:27 UTC
